name: CI

on:
  push:
    branches: [master, v2]
  pull_request:
    branches: [master, v2]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      # https://hexdocs.pm/elixir/1.17.2/compatibility-and-deprecations.html
      matrix:
        include:
          - pair:
              elixir: 1.14
              otp: 25.3
          - pair:
              elixir: 1.17
              otp: 27.0
            lint: lint

    services:
      postgres:
        image: postgres:16
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
      redis:
        image: redis
        ports: ['6379:6379']

    steps:
      - name: Start Default MySQL 5.7
        run: sudo /etc/init.d/mysql start

      - name: 'Wait for MySQL to be ready (TODO: needs timeout)'
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -uroot -proot -P3306 --silent >/dev/null 2>&1; do
            sleep 1
          done

      - name: Set up Elixir and OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.pair.otp }}
          elixir-version: ${{ matrix.pair.elixir }}
          version-type: strict

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore cache for deps/ and _build/ directories
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-test-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-test-${{ matrix.elixir }}-${{ matrix.otp }}-

      - name: Get deps
        run: mix deps.get --check-locked

      # TODO: lots of file will be changed
      # - name: Check format
      #   run: mix format --check-formatted
      #   if: ${{ matrix.lint }}

      - name: Check unused deps
        run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - name: Deps compilation
        run: mix deps.compile

      - name: Check compile warnings
        run: mix compile --no-optional-deps --warnings-as-errors
        if: ${{ matrix.lint }}

      - name: Run credo
        run: mix credo
        if: ${{ matrix.lint }}

      - name: Create and migrate the DB on Postgres
        run: |
          MIX_ENV=test PERSISTENCE=ecto RDBMS=postgres mix compile --warnings-as-errors
          MIX_ENV=test PERSISTENCE=ecto RDBMS=postgres mix do ecto.create, ecto.migrate
          rm -rf _build/test/lib/fun_with_flags

      - name: Create and migrate the DB on MySQL
        run: |
          MIX_ENV=test PERSISTENCE=ecto RDBMS=mysql mix compile --warnings-as-errors
          MIX_ENV=test PERSISTENCE=ecto RDBMS=mysql mix do ecto.create, ecto.migrate
          rm -rf _build/test/lib/fun_with_flags

      - name: Create and migrate the DB on SQLite
        run: |
          MIX_ENV=test PERSISTENCE=ecto RDBMS=sqlite mix compile --warnings-as-errors
          MIX_ENV=test PERSISTENCE=ecto RDBMS=sqlite mix do ecto.create, ecto.migrate
          rm -rf _build/test/lib/fun_with_flags

      - name: Run all tests
        run: mix test.all
